---

- name: Install Java
  include: java.yml

- name: Install Android SDK
  include: android-sdk.yml

- name: Install NodeJS
  include: nodejs.yml

- name: Install "Appium" node.js package.
  npm:
    name: appium
    version: '1.8.1'
    path: "{{ appium_install_location }}"
